### ISSUE TITLE
Missing meda query for Image

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#8] opened 2016-05-23 14:26 UTC
Image text is not readable at certain sizes

![image](https://cloud.githubusercontent.com/assets/1503577/15473987/093ffdc6-2103-11e6-8142-6cbc8c6b5348.png)

**Comment by serenader2014** [comment] 2016-05-23 14:33
Sorry I don't understand what the problem is. From your screenshot, it seems normal to me.

**Comment by jwillmer** [comment] 2016-05-23 14:36
ups, yes, on the left side of the image, the text, it ends with elevator but there is more text. It is hidden because the layout did not switch.

**Comment by serenader2014** [comment] 2016-05-23 14:37
Oh I see it. Will fix it later.

**Comment by serenader2014** [comment] 2016-05-23 16:20
Fixed in v1.1.2

**Closed as completed by serenader2014** 2016-05-23 16:20 UTC
